### ISSUE TITLE
config_template creation is broken

### ISSUE THREAD

**Issue by miroswan** [Apipie/apipie-bindings#34]
```
require 'apipie-bindings'

c = ApipieBindings::API.new(username: 'admin', password: 'admin', uri: 'https://192.168.33.66')

puts c.call(:domains, :create, domain: { name: 'thing' } )
puts c.call(:config_templates, :create, config_template: { name: 'thing', template: 'thing' } )

{"domain"=>{"created_at"=>"2016-02-15T20:59:37Z", "dns_id"=>nil, "fullname"=>nil, "hostgroups_count"=>0, "hosts_count"=>0, "id"=>5, "name"=>"thing", "updated_at"=>"2016-02-15T20:59:37Z"}}
/Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!': 422 Unprocessable Entity (RestClient::UnprocessableEntity)
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
	from /Users/demitri/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/rest-client-1.6.7/lib/restclient/resource.rb:67:in `post'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/apipie-bindings-0.0.15/lib/apipie_bindings/api.rb:285:in `call_client'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/apipie-bindings-0.0.15/lib/apipie_bindings/api.rb:216:in `http_call'
	from /Users/demitri/.rvm/gems/ruby-2.1.0@mozcookbook_foreman/gems/apipie-bindings-0.0.15/lib/apipie_bindings/api.rb:161:in `call'
	from bin/test.rb:6:in `<main>'
```

**Comment by miroswan** [comment]
rest-client library seems to be obfuscating the error. curl actually gives helpful output:

```
{
  "error": {"id":null,"errors":{"template_kind_id":["can't be blank"]},"full_messages":["Template kind can't be blank"]}
}
```

**Comment by miroswan** [comment]
It appears that api v2 fixes this.
